# Generated by Django 3.1.7 on 2021-03-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamenightapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='publishdate',
            field=models.CharField(max_length=4),
        ),
    ]
